### ISSUE TITLE
Tests fail with latest Cheerio (0.16.0)

### ISSUE THREAD

**Issue by dwabyick** [dlasky/grunt-dom-massager#1]
Hello, We used grunt-dom-massager, and then it suddenly broke.  I tracked this down to an update to Cheerio that is breaking grunt-dom-massager. The dependency is current "*" which is a bit loose. What I noticed is that 0.14.0 works, and 0.16.0 (the current one) does not. 

Simply checking out this repos and running test causes this problem.

**Comment by dwabyick** [comment]
See the following fork which fixes it. 
https://github.com/dwabyick/grunt-dom-massager

**Comment by dlasky** [comment]
merged your stuff in, let me know if you are still using it and i will publish. For some reason i never got notifications of this activity. Glad i was cleaning up old stuff and noticed it.
