### ISSUE TITLE
Typo in grunt.initConfig example in README

### ISSUE THREAD

**Issue by gamtiq** [dlasky/grunt-dom-massager#2]
There is a missing piece of configuration in the example inside [Overview](https://github.com/dlasky/grunt-dom-massager#overview) section.
Namely, `read_test` and `write_test` configurations should be inside `dom_massager` object.

**Comment by gamtiq** [comment]
Also it would be useful to add some keywords in `package.json` to improve searchability.
For example: `cheerio`, `dom`, `html`, `parse`

**Comment by dlasky** [comment]
thanks!
