### ISSUE TITLE
Some help please

### ISSUE THREAD

**Issue by timtribers** [dlasky/grunt-dom-massager#5]
Hi @dlasky 

Thanks for an awesome grunt task - this is doing just what I wanted.

But, just struggling to get a class added to an element.
If I use 
`action:"addClass", input: ["foo"]`
I get no errors, but also no class added :(
If I use 
`action:"attr", input:["foo","bar"]`
then I get my selector with attributes of 
`<mySelector 0="foo" 1="bar">`
No permutation of input options seems to work to give me
`<mySelector foo="bar">`

What am I doing wrong?

**Comment by dlasky** [comment]
@timtribers looks like a bug. should be fixed now, added test coverage as well. ping me if you have further issues and thanks for using it!

you'll need to update to `0.1.2`

**Comment by timtribers** [comment]
@dlasky Awesome!   Works like a dream.  Many thanks

**Comment by dlasky** [comment]
No worries. sorry for the initial trouble. embarrassing mistake.
