### ISSUE TITLE
Node 6 path problem

### ISSUE THREAD

**Issue by timtribers** [dlasky/grunt-dom-massager#7]
Hi there,

Just had to run a project containing dom-massager on a new machine build which has the latest Node LTS (6.10) and I find it now fails, with the error message "Warning: Path must be a string".  After a little digging, I find that other Grunt tasks are hitting this too (e.g. http://stackoverflow.com/questions/40145106/path-must-be-a-string-received-src-index-html).

It seems that this is because on Node 6.0.0 and higher, the path module accepts only string as input, and no longer allows an array with a single value.

Obviously I can just downgrade Node for now, but any chance of taking a look?

Many thanks,

**Comment by dlasky** [comment]
pushed 1.4, looks like path.basename was the main culprit. I haven't used this in prod in quite some time but it passes all the tests on node 4 and 6

**Comment by timtribers** [comment]
Many thanks for the very speedy fix.  It certainly seems to have address the file path issue under Node 6.  However, it has broken my project (under Node 6 and earlier Node versions too).  I am still trying to diagnose what's going on, but it seems to have changed the definition of 'this' inside functions on 'each' actions.  I can't at all see how your fix could have had such a knock-on effect.  Very strange.

**Comment by timtribers** [comment]
Ok, its not this fix that's broken things for me.  The problem was introduced in 0.1.3.

**Comment by timtribers** [comment]
It must be the bump up of cheerio version.  Perhaps cheerio has changed the way you have to do functions.  I will have to take a look.

**Comment by timtribers** [comment]
The cheerio readme now suggests that 'each' functions work like this:

```
$('li').each(function(i, elem) {
  fruits[i] = $(this).text();
});
```

I think that previously you could just do  **this.text()**  .

Anyway, the problem I now have in dom-massager, is that I can't do **$(this).text()** inside a function.  It just says that $ is undefined.  Using 'cheerio' instead of $ gives the same result.

How can I access cheerio in a dom-massager function?  Or, can you make 'this' a cheerio element again, so that I can just do **this.text()**?

I will copy this to a new issue.

Thanks.
