### ISSUE TITLE
Access cheerio in function

### ISSUE THREAD

**Issue by timtribers** [dlasky/grunt-dom-massager#8]
Hi Dan,

The cheerio readme suggests that 'each' functions work like this:

```
$('li').each(function(i, elem) {
  fruits[i] = $(this).text();
});
```

(I think that previously you could just do  **this.text()**  )

Anyway, the problem I have in dom-massager, is that I can't do **$(this).text()** inside a function.  It just says that $ is undefined.  Using 'cheerio' instead of $ gives the same result.

How can I access cheerio in a dom-massager function?  Or, can you make 'this' a cheerio element, so that I can just do **this.text()**?

Thanks.

**Comment by dlasky** [comment]
it seems like this is what you are asking for?

https://github.com/dlasky/grunt-dom-massager/blob/master/tasks/dom_massager.js#L76-L78

**Comment by timtribers** [comment]
Sorry for being so slow Dan, but I'm still not getting it.
I set cheerioHook true in the options - made no difference.  Does it need to be a function?

How would you config the above cheerio each() example to work in dom-massager?

- Tim

**Comment by dlasky** [comment]
it is indeed a function.

options.cheerioHook($, obj.html, grunt); is the signature, so you'd do something like

```
cheerioHook: function($, raw, grunt) {
var fruits = []
$('li').each(function(i, elem) {
  fruits[i] = $(this).text();
});
}
```

**Comment by timtribers** [comment]
Would be nice to have an approach that didn't so completely bypass dom-massager.
Something like this:
```
    dom_massager: {
      test: {
        options: {
          selectors: {
            'li': {
              action: 'each',
              input: [function(i, elem){
                fruits[i] = $(this).text();
              }]
            }
          }
        },
        files: {
          'output/': 'input/*.html'
        }
      }
    }
```
I.e. can cheerio be available as $ (or something else) within a function?

**Comment by dlasky** [comment]
it bypasses the element config because if you are doing an 'advanced' configuration like that there is no reason to have to pull all the individual selectors.

also since it seems like you are actually just doing extraction there is an output config designed to do that and push it into grunt config vars for you:

https://github.com/dlasky/grunt-dom-massager/blob/master/Gruntfile.js#L39-L42
